sudo: false
# use Ubuntu 14.04 (Trusty) image, it contains the latest JDK
dist: trusty
language: java

before_install:
  # start X-server for GUI tests (xvfb)
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  # get latest install-jdk.sh script
  - wget https://github.com/sormuras/bach/raw/master/install-jdk.sh

# Java 10 "Oracle JDK" (not yet provided by Travis CI)
matrix:
  include:
    - env: oraclejdk10
      env: JDK_RELEASE='Oracle JDK 10'
      install: . ./install-jdk.sh -F 10 -L BCL

# print environment setup
script:
  - echo PATH = ${PATH}
  - echo JAVA_HOME = ${JAVA_HOME}
  - java -version
